services:
  db:
    image: postgres:15
    container_name: aura_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Saladas.2
      POSTGRES_DB: aura_db
    ports:
      - "5432:5432"
    volumes:
      - aura_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: aura_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:Saladas.2@db:5432/aura_db"
      JWT_SECRET: "change-me-please"
      ADMIN_EMAIL: "dr.kelven@aura.app"
      ADMIN_PASSWORD: "aura123"
      ADMIN_NAME: "Dr. Kelven"
      ENVIRONMENT: "prod"

volumes:
  aura_db_data:
